const Joi = require("joi");

module.exports.customerSchema = Joi.object({
    customer_name: Joi.string().required(),
    primary_phone: Joi.string().required(),
    secondary_phone: Joi.string().allow(''),
    fax: Joi.string().allow(''),
    website: Joi.string().allow(''),
    email:Joi.string().allow(''),
    notes: Joi.string().allow(''),
    status: Joi.string().required(),
    county: Joi.string().required(),
    billing_one: Joi.string().required(),
    billing_two: Joi.string().allow(''),
    billing_city: Joi.string().required(),
    billing_state: Joi.string().required(),
    billing_zip: Joi.string().required(),
    billing_country: Joi.string().required(),
    shipping_one: Joi.string().allow(''),
    shipping_two: Joi.string().allow(''),
    shipping_city: Joi.string().allow(''),
    shipping_state: Joi.string().allow(''),
    shipping_zip: Joi.string().allow(''),
    shipping_country: Joi.string().allow(''),
    added_by: Joi.string().required(),
    updated_by: Joi.string().required(),
});
