CREATE TABLE `products` (
	`name` VARCHAR(240) NOT NULL COLLATE 'utf8mb3_unicode_520_ci'
)
COLLATE='utf8mb3_unicode_520_ci'
ENGINE=InnoDB
;

INSERT INTO `products` VALUES ('AVAST PRO');
INSERT INTO `products` VALUES ('AVAST ENDPOINT');
INSERT INTO `products` VALUES ('MALWAREBYTES');
INSERT INTO `products` VALUES ('MICROSOFT OFFICE 2010');
INSERT INTO `products` VALUES ('MICROSOFT OFFICE 2013');
INSERT INTO `products` VALUES ('MICROSOFT OFFICE 2016');
INSERT INTO `products` VALUES ('MICROSOFT OFFICE 2019');
INSERT INTO `products` VALUES ('MICROSOFT OFFICE 365');